version: '3.8'
services:
  app:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    container_name: notify-chat-service
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URI=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      - REDIS_URI=redis://redis:6379/0
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: notify-chat-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: notify-chat-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
